import Head from 'next/head'
import Image from 'next/image'
import classnames from 'classnames'
import { Inter } from 'next/font/google'
import styles from '~/styles/Home.module.css'
import DailyCard from '~/components/DailyCard'
import localFont from 'next/font/local'

const inter = Inter({ subsets: ['latin'] })
const MiSansFont = localFont({
  src: [{
    path: './MiSans-Thin.ttf',
    weight: '100',
    style: 'thin',
  }, {
    path: './MiSans-Normal.ttf',
    weight: '300',
    style: 'Normal',
  }, {
    path: './MiSans-Medium.ttf',
    weight: '500',
    style: 'Medium',
  }, {
    path: './MiSans-Bold.ttf',
    weight: '700',
    style: 'Bold',
  }, {
    path: './MiSans-Heavy.ttf',
    weight: '900',
    style: 'Heavy',
  }]
})

export default function Home() {

  return (
    <>
      <Head>
        <title>Elf Design</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={classnames(styles.main, MiSansFont.className)}>
        <div className={styles.router}>

        </div>
        <div className={styles.article}>
          <DailyCard />
        </div>
      </main >
    </>
  )
}
